/* eslint-disable no-restricted-imports */
import {
  IconHome,
  IconSettings,
  IconWallet,
  IconArrowsExchange,
  IconChartBar,
  IconTarget,
  IconTrendingUp,
  IconTrendingDown,
  IconChartPie,
  IconFileText,
  IconFileTypePdf,
  IconBuildingBank,
  IconDatabase,
  IconTags,
  IconCategory,
  IconAdjustments,
  IconPlus,
  IconPencil,
  IconTrash,
  IconX,
  IconCheck,
  IconDownload,
  IconUpload,
  IconRefresh,
  IconSearch,
  IconFilter,
  IconSortDescending,
  IconChevronRight,
  IconChevronDown,
  IconChevronLeft,
  IconChevronUp,
  IconMenu2,
  IconEye,
  IconEyeOff,
  IconCopy,
  IconExternalLink,
  IconGripVertical,
  IconHash,
  IconAlertCircle,
  IconAlertTriangle,
  IconInfoCircle,
  IconCircleCheck,
  IconCircleX,
  IconBell,
  IconBellOff,
  IconCreditCard,
  IconCash,
  IconReceipt,
  IconPigMoney,
  IconCoins,
  IconCurrencyDollar,
  IconCurrencyPound,
  IconCashBanknote,
  IconBusinessplan,
  IconReportMoney,
  IconMoneybag,
  IconBulb,
  IconCalculator,
  IconRepeat,
  IconChartLine,
  IconChartArea,
  IconChartDonut,
  IconReportAnalytics,
  IconPresentation,
  IconPalette,
  IconCalendar,
  IconClock,
  IconCalendarEvent,
  IconHistory,
  IconUser,
  IconUsers,
  IconUserCircle,
  IconLogin,
  IconLogout,
  IconLock,
  IconLockOpen,
  IconShield,
  IconShieldCheck,
  IconKey,
  IconKeyboard,
  IconBriefcase,
  IconBuilding,
  IconFileInvoice,
  IconFolder,
  IconFolderPlus,
  IconArchive,
  IconDeviceDesktop,
  IconLayoutGrid,
  IconActivity,
  IconLayersLinked,
  IconArrowsLeftRight,
  IconArrowUp,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUpRight,
  IconArrowDownRight,
  IconWand,
  IconDeviceFloppy,
  IconTool,
  IconMaximize,
  IconMinimize,
  IconPlayerPlay,
  IconPlayerStop,
  IconHeart,
  IconPill,
  IconMoon,
  IconSun,
  IconWorld,
  IconLink,
  IconVolume,
  IconMail,
  IconPhone,
  IconWifi,
  IconMapPin,
  IconCar,
  IconSchool,
  IconFlag,
  IconStar,
  IconAward,
  IconTrophy,
  IconCertificate,
  IconFingerprint,
} from '@tabler/icons-react';

export const ICON_CONFIG = {
  size: 20,
  stroke: 2,
  className: 'transition-colors duration-200',
} as const;

export const iconMap = {
  home: IconHome,
  dashboard: IconChartBar,
  transactions: IconArrowsExchange,
  accounts: IconBuildingBank,
  budget: IconChartPie,
  goals: IconTarget,
  investments: IconTrendingUp,
  analytics: IconChartLine,
  reports: IconFileText,
  document: IconFileText,
  settings: IconSettings,
  settingsAlt: IconAdjustments,
  database: IconDatabase,
  tags: IconTags,
  categories: IconCategory,
  add: IconPlus,
  edit: IconPencil,
  delete: IconTrash,
  close: IconX,
  check: IconCheck,
  download: IconDownload,
  upload: IconUpload,
  refresh: IconRefresh,
  search: IconSearch,
  filter: IconFilter,
  sort: IconSortDescending,
  chevronRight: IconChevronRight,
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronUp: IconChevronUp,
  menu: IconMenu2,
  eye: IconEye,
  eyeOff: IconEyeOff,
  copy: IconCopy,
  externalLink: IconExternalLink,
  grip: IconGripVertical,
  hash: IconHash,
  info: IconInfoCircle,
  warning: IconAlertTriangle,
  error: IconAlertCircle,
  success: IconCircleCheck,
  close2: IconCircleX,
  notification: IconBell,
  notificationOff: IconBellOff,
  creditCard: IconCreditCard,
  cash: IconCash,
  receipt: IconReceipt,
  piggyBank: IconPigMoney,
  coins: IconCoins,
  dollar: IconCurrencyDollar,
  pound: IconCurrencyPound,
  banknote: IconCashBanknote,
  businessPlan: IconBusinessplan,
  moneyReport: IconReportMoney,
  wallet: IconWallet,
  moneyBag: IconMoneybag,
  calculator: IconCalculator,
  repeat: IconRepeat,
  trendingUp: IconTrendingUp,
  trendingDown: IconTrendingDown,
  activity: IconActivity,
  chartArea: IconChartArea,
  chartDonut: IconChartDonut,
  analyticsReport: IconReportAnalytics,
  lightbulb: IconBulb,
  presentation: IconPresentation,
  palette: IconPalette,
  calendar: IconCalendar,
  clock: IconClock,
  event: IconCalendarEvent,
  history: IconHistory,
  user: IconUser,
  users: IconUsers,
  userCircle: IconUserCircle,
  login: IconLogin,
  logout: IconLogout,
  lock: IconLock,
  unlock: IconLockOpen,
  shield: IconShield,
  shieldCheck: IconShieldCheck,
  key: IconKey,
  keyboard: IconKeyboard,
  briefcase: IconBriefcase,
  building: IconBuilding,
  invoice: IconFileInvoice,
  folder: IconFolder,
  folderPlus: IconFolderPlus,
  archive: IconArchive,
  pdf: IconFileTypePdf,
  desktop: IconDeviceDesktop,
  moon: IconMoon,
  sun: IconSun,
  globe: IconWorld,
  link: IconLink,
  volume: IconVolume,
  mail: IconMail,
  phone: IconPhone,
  wifi: IconWifi,
  location: IconMapPin,
  car: IconCar,
  education: IconSchool,
  flag: IconFlag,
  star: IconStar,
  award: IconAward,
  trophy: IconTrophy,
  certificate: IconCertificate,
  fingerprint: IconFingerprint,
  chartLine: IconChartLine,
  chartBar: IconChartBar,
  chartPie: IconChartPie,
  grid: IconLayoutGrid,
  layers: IconLayersLinked,
  arrowsLeftRight: IconArrowsLeftRight,
  arrowUp: IconArrowUp,
  arrowDown: IconArrowDown,
  arrowLeft: IconArrowLeft,
  arrowRight: IconArrowRight,
  arrowUpRight: IconArrowUpRight,
  arrowDownRight: IconArrowDownRight,
  save: IconDeviceFloppy,
  maximize: IconMaximize,
  minimize: IconMinimize,
  play: IconPlayerPlay,
  stop: IconPlayerStop,
  tool: IconTool,
  heart: IconHeart,
  pill: IconPill,
  magicWand: IconWand,
} as const;

export type ProfessionalIconName = keyof typeof iconMap;
