version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    open-pull-requests-limit: 5
    target-branch: "develop"
    labels:
      - dependencies
      - needs-approval
    commit-message:
      prefix: "build"
      include: "scope"
    versioning-strategy: increase
    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "vite"
      - dependency-name: "typescript"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

