export { IconBase } from './IconBase';
export type { IconProps } from './IconBase';

export { SettingsIcon } from './SettingsIcon';
export { DeleteIcon } from './DeleteIcon';
export { EditIcon } from './EditIcon';
export { PlusIcon } from './PlusIcon';
export { ExpandIcon } from './ExpandIcon';
export { ShrinkIcon } from './ShrinkIcon';
export { MaximizeIcon } from './MaximizeIcon';
export { MinimizeIcon } from './MinimizeIcon';

// Re-export commonly used icons with alternative names
export { XIcon } from './XIcon';
export { CheckIcon } from './CheckIcon';
export { ChevronRightIcon } from './ChevronRightIcon';
export { ChevronDownIcon } from './ChevronDownIcon';
export { ChevronLeftIcon } from './ChevronLeftIcon';
export { ArrowLeftIcon } from './ArrowLeftIcon';
export { CheckCircleIcon } from './CheckCircleIcon';
export { Building2Icon } from './Building2Icon';
export { CreditCardIcon } from './CreditCardIcon';
export { CircleDotIcon } from './CircleDotIcon';
export { TrendingUpIcon } from './TrendingUpIcon';
export { TrendingDownIcon } from './TrendingDownIcon';
export { AlertCircleIcon } from './AlertCircleIcon';
export { CalendarIcon } from './CalendarIcon';
export { BanknoteIcon } from './BanknoteIcon';
export { TagIcon } from './TagIcon';
export { HashIcon } from './HashIcon';
export { SearchIcon } from './SearchIcon';
export { WalletIcon } from './WalletIcon';
export { PiggyBankIcon } from './PiggyBankIcon';
export { HomeIcon } from './HomeIcon';
export { ChevronUpIcon } from './ChevronUpIcon';
export { FileTextIcon } from './FileTextIcon';
export { TargetIcon } from './TargetIcon';
export { AlertTriangleIcon } from './AlertTriangleIcon';
export { ArrowRightIcon } from './ArrowRightIcon';
export { ArrowRightLeftIcon } from './ArrowRightLeftIcon';
export { ArrowUpRightIcon } from './ArrowUpRightIcon';
export { ArrowDownRightIcon } from './ArrowDownRightIcon';
export { BarChart3Icon } from './BarChart3Icon';
export { CalculatorIcon } from './CalculatorIcon';
export { CheckIcon2 } from './CheckIcon2';
export { ClockIcon } from './ClockIcon';
export { DatabaseIcon } from './DatabaseIcon';
export { DownloadIcon } from './DownloadIcon';
export { EyeIcon } from './EyeIcon';
export { EyeOffIcon } from './EyeOffIcon';
export { FilterIcon } from './FilterIcon';
export { GlobeIcon } from './GlobeIcon';
export { GoalIcon } from './GoalIcon';
export { GripVerticalIcon } from './GripVerticalIcon';
export { InfoIcon } from './InfoIcon';
export { LandmarkIcon } from './LandmarkIcon';
export { LineChartIcon } from './LineChartIcon';
export { LinkIcon } from './LinkIcon';
export { MenuIcon } from './MenuIcon';
export { MonitorIcon } from './MonitorIcon';
export { MoonIcon } from './MoonIcon';
export { PaletteIcon } from './PaletteIcon';
export { PieChartIcon } from './PieChartIcon';
export { PlusCircleIcon } from './PlusCircleIcon';
export { RefreshCwIcon } from './RefreshCwIcon';
export { RepeatIcon } from './RepeatIcon';
export { Settings2Icon } from './Settings2Icon';
export { SunIcon } from './SunIcon';
export { UploadIcon } from './UploadIcon';
export { XCircleIcon } from './XCircleIcon';

// Re-export commonly used icons with alternative names
export { DeleteIcon as TrashIcon } from './DeleteIcon';
export { EditIcon as PencilIcon } from './EditIcon';
export { MaximizeIcon as Maximize2Icon } from './MaximizeIcon';
export { MinimizeIcon as Minimize2Icon } from './MinimizeIcon';
export { EditIcon as Edit2Icon } from './EditIcon';
export { DeleteIcon as Trash2Icon } from './DeleteIcon';
export { TagIcon as Tag } from './TagIcon';
export { CheckIcon2 as Check } from './CheckIcon2';
export { BarChart3Icon as BarChart3 } from './BarChart3Icon';
export { PiggyBankIcon as PiggyBank } from './PiggyBankIcon';
export { WalletIcon as Wallet } from './WalletIcon';
export { HomeIcon as Home } from './HomeIcon';
export { SearchIcon as Search } from './SearchIcon';
export { CalendarIcon as Calendar } from './CalendarIcon';
export { FileTextIcon as FileText } from './FileTextIcon';
export { TargetIcon as Target } from './TargetIcon';
export { LinkIcon as Link } from './LinkIcon';
export { ClockIcon as Clock } from './ClockIcon';
export { DatabaseIcon as Database } from './DatabaseIcon';
export { DownloadIcon as Download } from './DownloadIcon';
export { EyeIcon as Eye } from './EyeIcon';
export { EyeOffIcon as EyeOff } from './EyeOffIcon';
export { FilterIcon as Filter } from './FilterIcon';
export { GlobeIcon as Globe } from './GlobeIcon';
export { GoalIcon as Goal } from './GoalIcon';
export { GripVerticalIcon as GripVertical } from './GripVerticalIcon';
export { InfoIcon as Info } from './InfoIcon';
export { LandmarkIcon as Landmark } from './LandmarkIcon';
export { LineChartIcon as LineChart } from './LineChartIcon';
export { MenuIcon as Menu } from './MenuIcon';
export { MonitorIcon as Monitor } from './MonitorIcon';
export { MoonIcon as Moon } from './MoonIcon';
export { PaletteIcon as Palette } from './PaletteIcon';
export { PieChartIcon as PieChart } from './PieChartIcon';
export { RefreshCwIcon as RefreshCw } from './RefreshCwIcon';
export { RepeatIcon as Repeat } from './RepeatIcon';
export { Settings2Icon as Settings2 } from './Settings2Icon';
export { SunIcon as Sun } from './SunIcon';
export { UploadIcon as Upload } from './UploadIcon';
export { XCircleIcon as XCircle } from './XCircleIcon';
export { CalculatorIcon as Calculator } from './CalculatorIcon';
export { AlertTriangleIcon as AlertTriangle } from './AlertTriangleIcon';
export { ArrowRightIcon as ArrowRight } from './ArrowRightIcon';
export { ArrowRightLeftIcon as ArrowRightLeft } from './ArrowRightLeftIcon';
export { ArrowUpRightIcon as ArrowUpRight } from './ArrowUpRightIcon';
export { ArrowDownRightIcon as ArrowDownRight } from './ArrowDownRightIcon';
export { BanknoteIcon as Banknote } from './BanknoteIcon';
export { ChevronUpIcon as ChevronUp } from './ChevronUpIcon';
export { PlusCircleIcon as PlusCircle } from './PlusCircleIcon';
export { SettingsIcon as Settings } from './SettingsIcon';
export { XIcon as X } from './XIcon';
export { ArrowLeftIcon as ArrowLeft } from './ArrowLeftIcon';
export { MaximizeIcon as Maximize2 } from './MaximizeIcon';
export { ChevronRightIcon as ChevronRight } from './ChevronRightIcon';
export { TrendingUpIcon as TrendingUp } from './TrendingUpIcon';
export { TrendingDownIcon as TrendingDown } from './TrendingDownIcon';
export { AlertCircleIcon as AlertCircle } from './AlertCircleIcon';
export { CheckCircleIcon as CheckCircle } from './CheckCircleIcon';
export { CreditCardIcon as CreditCard } from './CreditCardIcon';
export { HashIcon as Hash } from './HashIcon';
export { LockIcon } from './LockIcon';
export { UnlockIcon } from './UnlockIcon';
export { LockIcon as Lock } from './LockIcon';
export { UnlockIcon as Unlock } from './UnlockIcon';
export { WifiOffIcon } from './WifiOffIcon';
export { WifiOffIcon as WifiOff } from './WifiOffIcon';
export { ComputerIcon } from './ComputerIcon';
export { ComputerIcon as Computer } from './ComputerIcon';
export { KeyboardIcon } from './KeyboardIcon';
export { KeyboardIcon as Keyboard } from './KeyboardIcon';
export { MinusIcon } from './MinusIcon';
export { MinusIcon as Minus } from './MinusIcon';
export { DollarSignIcon } from './DollarSignIcon';
export { DollarSignIcon as DollarSign } from './DollarSignIcon';
export { SaveIcon } from './SaveIcon';
export { SaveIcon as Save } from './SaveIcon';
export { LayersIcon } from './LayersIcon';
export { LayersIcon as Layers } from './LayersIcon';
export { GridIcon } from './GridIcon';
export { GridIcon as Grid } from './GridIcon';
export { MagicWandIcon } from './MagicWandIcon';
export { MagicWandIcon as MagicWand } from './MagicWandIcon';
export { BellIcon } from './BellIcon';
export { BellIcon as Bell } from './BellIcon';
export { VolumeIcon } from './VolumeIcon';
export { VolumeIcon as Volume } from './VolumeIcon';
export { BellOffIcon } from './BellOffIcon';
export { BellOffIcon as BellOff } from './BellOffIcon';
export { CopyIcon } from './CopyIcon';
export { CopyIcon as Copy } from './CopyIcon';
export { PlayIcon } from './PlayIcon';
export { PlayIcon as Play } from './PlayIcon';
export { StopIcon } from './StopIcon';
export { StopIcon as Stop } from './StopIcon';
export { MergeIcon } from './MergeIcon';
export { MergeIcon as Merge } from './MergeIcon';
export { SelectAllIcon } from './SelectAllIcon';
export { SelectAllIcon as SelectAll } from './SelectAllIcon';
export { DeselectAllIcon } from './DeselectAllIcon';
export { DeselectAllIcon as DeselectAll } from './DeselectAllIcon';
export { UnlinkIcon } from './UnlinkIcon';
export { UnlinkIcon as Unlink } from './UnlinkIcon';
export { WrenchIcon } from './WrenchIcon';
export { WrenchIcon as Wrench } from './WrenchIcon';
export { FolderIcon } from './FolderIcon';
export { FolderIcon as Folder } from './FolderIcon';
export { UndoIcon } from './UndoIcon';
export { UndoIcon as Undo } from './UndoIcon';