-- Initial Schema Placeholder
-- Generated: 2025-10-30T00:38:14.454Z
--
-- This is a placeholder migration file. To capture the full schema with RLS policies,
-- triggers, functions, and constraints, you need to:
--
-- 1. Get the database password from Supabase Dashboard:
--    - Go to Settings → Database → Connection string
--    - Copy the password from the connection string
--
-- 2. Export the database URL:
--    export SUPABASE_DB_URL="postgresql://postgres:<password>@db.nqbacrjjgdjabygqtcah.supabase.co:5432/postgres"
--
-- 3. Run the schema dump:
--    npx supabase db dump --db-url "$SUPABASE_DB_URL" --schema public --data false --file supabase/migrations/20251030003814__initial-schema.sql
--
-- 4. Replace this file with the generated schema dump
--
-- Tables confirmed to exist in the database:
-- - profiles
-- - accounts
-- - transactions
-- - categories
-- - budgets
-- - budget_periods
-- - goals
-- - financial_plans
-- - bills
-- - investments
-- - investment_transactions
-- - tags
-- - transaction_tags
-- - import_rules
--
-- Note: The actual schema includes RLS policies, triggers, functions, and constraints
-- that cannot be exported via the Supabase JS client API.
