name: PR Guardrails (Danger)

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  danger:
    name: Run DangerJS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Danger
        uses: danger/danger-js@11.4.0
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

